---
title: "Project 5 Gene interaction"
author: "Melissa Kang and Seth Peacock"
date: "2022-08-11"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Introduction and Problem Statement (1 paragraph)
Genes are fundamental to cell biology. Some gene may cause others to not be express, repress, some may cause them to be expressed more, activate, some may repress or activate themselves, or have no interaction with other genes. Key genes determine cell development. Considering many genes in a cell together, a (one-direction) network can model the interactions between the genes, where an edge may indicate activation or indicate repression. A large network of many genes is build up from network motifs between pairs of genes. Knowing these motifs, then, can inform modeling of large gene networks and and understanding cell development. The network links, however, not so clear that they can be observed directly. What can be observed is the number of gene A and gene B across many cells. These provide counts which may be transformed to estimate a bivariate probability mass function (pmf) for the two genes. The bivariate pmf is, in part, the result of the underlying motif. Predicting the motif based on the pmf may, therefore, be possible. The To this end, we used supervised machine learning to predict the motif given the pmf. This required that we know the underlining motif, so the Read Lab estimated the pmfs for the motifs using simulation. 

Prediction-modeling performance is pending.


## Background and related work (1 or 2 paragraphs)
Describe relevant scientific background and point to work that tried to solve similar problems in the past. Provide a few references to textbooks and/or research articles that describe relevant background. 


Stochastic models of gene regulatory networks have been tremendously influential towards understanding cellular heterogeneity and analyzing data from single-cell RNA sequencing (scRNA-seq). In order to further understand single-cell gene pair interactions, stochastic models have been used to produce gene-pair co-expression landscapes from a bivariate distribution (Gallivan et al. (2020)). Gallivan et al. have developed a family of stochastic gene-gene interaction models because existing single-cell data analysis techniques have mostly disregarded that pair-wise gene interactions can be deduced from the shapes of these landscapes (2020). Shannon Entropy, Peason Correlation Coefficient, Mutual Information, and a Coexpression Index were found to be relatively inaccurate predictors of landscape shape of a gene-gene interaction on their own, so the student researchers added mean and standard deviation to the list of features to train the models (Gallivan et al. (2020)). 

In another relevant article, Cao, J., Spielmann, M., Qiu, X. et al. have used scRNA-seq on two million cells from mouse embryo in attempt to obtain a more comprehensive view of the mouse oranogenesis cell atlas (MOCA) and developmental processes (Cao, J., Spielmann, M., Qiu, X. et al. (2019)). The student researchers have used the data collected for this experiment to visualize the gene-pair bivariate pmfs used for the stochastic models and to test whether the models trained on the simulated data can distinguish the motif of a landscape. 


## Data and exploratory data analysis
Describe what data set(s) you used in the project – include references (e.g., URLs) for where you obtained the data if you can.  This section should have considerable detail – make sure you include a good description of your data set(s), including size, dimensionality, types of variables, etc. 
Use figures (histograms, scatter plots, etc) and tables, but do not overwhelm the reader with too many plots and show only plots that provide interesting insights. In your writing, try to give the reader some intuition and sense of what your data is like.

```{python}
import h5py
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
import os
```


### Experimental Data

The data was transformed into a h5 file from https://oncoscape.v3.sttrcancer.org/atlas.gs.washington.edu.mouse.rna/downloads gene_count.txt.  

```{python}

filename = '../data/hepatocyte_data.h5'

hdf = h5py.File(filename, mode = 'r')
# hdf.keys(): 'Hepatocyte trajectory'

d1 = hdf['Hepatocyte trajectory']

# d1.keys(): ['assay_data', 'col_labels', 'row_labels']

assay_data = d1['assay_data']
# assay_data.keys(): ['data', 'indices', 'indptr']

data = assay_data['data']
indices = assay_data['indices']
indptr = assay_data['indptr']

sparse = csr_matrix((data, indices, indptr))
sparse_size = sparse.shape
```

The rows of the sparse matrix are cells, and the columns are genes. The dataset is (11376, 26183), so there are 11376 cells and 26183 genes. The dataset from the h5 file has been transformed into a sparse matrix, but a sample of it is not shown here because it is mostly zeroes. Instead, the histogram below shows the distribution of values in the sparse matrix. The 2d plot was created from the entire sparse matrix and reinforces the idea that some genes are more commonly expressed than others. This is shown by the vertical striations seen in the graph for genes that are expressed in many cells. Other genes are seen as whitespace because they are hardly expressed at all.

```{python}
#fig, ax = plt.subplots(figsize=(10, 7))
#sns.histplot(csr_matrix.toarray().reshape(-1), bins=50)
#ax.set_yscale('log')
#plt.xlabel('probabilty')
#plt.show()
```

![]{'../analysis/eda/h5-plots/gene_count.png'}
![]{'../analysis/eda/h5-plots/('../analysis/eda/h5-plots/2d-plot.png'}

```{python}
row_labels = d1['row_labels']

rows = np.array(row_labels)

df = pd.DataFrame.sparse.from_spmatrix(sparse)
num_cols = df.shape[1]

# series containing the number of cells that express the 
# corresponding gene
num_genes = pd.Series()

for gene, data in df.iteritems():
    cell_count = pd.Series((data != 0).sum())
    num_genes = num_genes.append(cell_count)

num_genes.index = [i for i in range(0, num_cols)]

# get top 26 most expressed gene
most_expressed = num_genes.nlargest(n = 26)

top_26_matrix = []

for gene, count in most_expressed.iteritems():
    top_26_matrix.append(df.loc[:, gene])

# rows: genes
# cols: cells
top_26_df = pd.DataFrame(top_26_matrix)

print(top_26_df.head())
```

The top_26_df is a Dataframe of the 26 most expressed genes in the sparse matrix. There are 26 rows for the 26 genes and there are 11376 columns for the original amount of cells. This Dataframe was used to create gene-gene interaction heatmap plots for each distinct interaction between the 26 genes. The axis of the plots are the gene counts and the coloring scale represents the number of cells with the combination of gene counts. Below are two of the plots made.

From the afp vs meg3 plot, we can infer that cells that express a large amount of Afp also tend to express a large amount of Meg3. Therefore, we are expecting a motif identifier that expresses a fairly equal relationship between the two genes. The meg3 vs gpc3 plot shows that cells that express a large amount of Gpc3 tend to express a lower amount of Meg3, so we expect a motif identifer that favors one of the genes over the other. 

![]{'../analysis/eda/h5-plots/Gene1-Afp-vs-Gene2-Meg3-hm.png'}
![]{'../analysis/eda/h5-plots/Gene1-Meg3-vs-Gene2-Gpc3-hm.png'}

### Simulated Data
These data were generated by the Read Lab using the stochastic model which Gallivan et al. introduced (2019). We used multiple simulated data sets. The first we received (hereafter ) had pmf estimates for all 81 gene pair motifs, approximately 60 replicates, each using different rate parameters, per motif. The pmf's domain was two counts, starting at zero and truncated at fifty. This pmf was vectorized (length 2601). Each of the columns, then, has the estimated probability that a given cell would have $x_i$ gene X and $y_i$ of Y for the rates specified for that replicate. We added to each row the motif identifier, which is four digits. The first digit identifies what gene X does to itself, the second what gene X does to gene Y, the third what Y does to X, and the fourth what Y does to itself. Each digit may be 1 for activation, 0 for not interaction, or -1 for repression. Here is the first five rows of the data frame.

```{python Simulated Data Sample, echo=FALSE}
data_path = ['..', 'data']

x = [ i for i in range(51) for _ in range(51)]
y = [ i for _ in range(51) for i in range(51)]

columns = ['p(X=%s,Y=%s)' % (i, j) for i, j in zip(x,y)]

data_1 = pd.read_table(os.path.join(*data_path, 'SyntheticData_FirstSet.txt'),
                       delimiter='   ',
                       names=columns,
                       dtype=float,
                       engine='python')

motif_labels = pd.read_table(os.path.join(*data_path, 'membership.txt'),
                             delimiter='   ',
                             names=['motif'],
                             dtype=int,
                             engine='python')


network_motifs = pd.read_table(os.path.join(*data_path, 'NetworkMotifs.txt'),
                             delimiter='  ',
                             names=['i0', 'i1', 'i2', 'i3'],
                             dtype=int,
                             engine='python')

network_motifs = pd.DataFrame(network_motifs.apply(lambda x: '{} {} {} {}'.format(*x), axis=1),
    columns=['motif_identifier'])

network_motifs.index += 1

motif_labels = pd.merge(motif_labels.loc[:, 'motif'], network_motifs, how='left', left_on='motif', right_index=True)
data_1 = pd.merge(motif_labels, data_1, how='right', left_index=True, right_index=True)

print(data_1.loc[:, 'motif_identifier':].head())
```

The probabilities for a row may be transformed to a 51x51 matrix and visualize using heatmap, such as the following.


![]{../analysis/eda/first-set-heatmaps/sample/motif-06-#00-index-4080.png}
For this replicate, having counts around 30 are likely for gene Y and 4 for X.
![]{../analysis/eda/first-set-heatmaps/sample/motif-06-#01-index-3584.png}
Most of the mass is around p(X=0,Y=0).

```{python eval=FALSE, include=FALSE}
fig, ax = plt.subplots(figsize=(10, 7))
sns.histplot(data_1.loc[:, 'p(X=0,Y=0)':].to_numpy().reshape(-1), bins=50)
ax.set_yscale('log')
plt.title('Historgram of Probabilites')
plt.xlabel('probabilty')
plt.show()
```

The following are summary statistics of two motifs.
![]{../analysis/eda/first-set-heatmaps/summaries/08-mean.png}
![]{../analysis/eda/first-set-heatmaps/summaries/08-std.png}

This motif varies quite a bit.

![]{../analysis/eda/first-set-heatmaps/summaries/57-mean.png}
![]{../analysis/eda/first-set-heatmaps/summaries/57-std.png}

This one is mutual repression, self activation.

## Methods
Provide a description of the technical/methodological approach that chose for your project. State assumptions clearly. 



## Resutls
Describe inferential and/or predictive results of your analysis. Try to avoid showing large tables and use graphics if possible instead. 


## Discussion and Conclusion 
Discuss what insights you gained from your project, in bullet form as follows:
- Provide summary of your findings
- What are limitations of your analyses? How can they be remedied in the future work?

 
